# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0943d641aeebfe859198c3525ca55d4e2f9267fb57ce9761dea2e2f3685a68570832442842d61269b515be0b5751b53fb3c6a2538a075f44f36f93c5276820c

test:
  secret_key_base: 4dc1151f181b82b34b3a318c8dda563d9a4eff1a9d8907730d8aaa6c228b33291b1881a6c40ddbbbd09b7f8a7182dbca71cd076ceccce1366ad821594bda2c6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
